version: "3.9"

networks:
  presence-bot-net:
    driver: bridge

services:
  presence-monitor-dotnet:
    build:
      context: ./
      dockerfile: Dockerfile
    image: presence-monitor-dotnet:latest
    restart: always
    environment:
      - MqttOptions__Url=test.mosquitto.org
      - MqttOptions__Topic=+/time
      - mqttOptions__Port=1883
    networks:
      - presence-bot-net